export const OPEN_CART_DRAWER = 'OPEN_CART_DRAWER';
export const CLOSE_CART_DRAWER = 'CLOSE_CART_DRAWER';

export const OPEN_FAVORITES_DRAWER = 'OPEN_FAVORITES_DRAWER';
export const CLOSE_FAVORITES_DRAWER = 'CLOSE_FAVORITES_DRAWER';
