export const OPEN_CART_DRAWER = 'drawer/OPEN_CART_DRAWER';
export const CLOSE_CART_DRAWER = 'drawer/CLOSE_CART_DRAWER';

export const OPEN_FAVORITES_DRAWER = 'drawer/OPEN_FAVORITES_DRAWER';
export const CLOSE_FAVORITES_DRAWER = 'drawer/CLOSE_FAVORITES_DRAWER';

export const SET_REDIRECT_AFTER_LOGIN = 'drawer/SET_REDIRECT_AFTER_LOGIN';
export const CLEAR_REDIRECT_AFTER_LOGIN = 'drawer/CLEAR_REDIRECT_AFTER_LOGIN';
