export const ADD_TO_CART_REQUEST = 'cart/ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'cart/ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'cart/ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_REQUEST = 'cart/REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'cart/REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'cart/REMOVE_FROM_CART_FAILURE';

export const UPDATE_CART_ITEM_REQUEST = 'cart/UPDATE_CART_ITEM_REQUEST';
export const UPDATE_CART_ITEM_SUCCESS = 'cart/UPDATE_CART_ITEM_SUCCESS';
export const UPDATE_CART_ITEM_FAILURE = 'cart/UPDATE_CART_ITEM_FAILURE';

export const CLEAR_CART = 'cart/CLEAR_CART';
