export const FETCH_CART_REQUEST = "cart/FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "cart/FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE = "cart/FETCH_CART_FAILURE";

export const ADD_TO_CART_REQUEST = "cart/ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "cart/ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "cart/ADD_TO_CART_FAILURE";

export const REMOVE_FROM_CART_REQUEST = "cart/REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "cart/REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "cart/REMOVE_FROM_CART_FAILURE";

export const UPDATE_CART_ITEM_REQUEST = "cart/UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "cart/UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILURE = "cart/UPDATE_CART_ITEM_FAILURE";

export const CLEAR_CART = "cart/CLEAR_CART";
export const SET_CART = "cart/SET_CART";
export const SET_FINAL_CART = "cart/SET_FINAL_CART";
export const SET_EURO_RATE = "cart/SET_EURO_RATE";
export const SET_SELECTED_ADDRESS = "cart/SET_SELECTED_ADDRESS";
export const SET_PAYMENT_METHOD = "cart/SET_PAYMENT_METHOD";
export const ADD_TO_CART = "cart/ADD_TO_CART";
