export const FETCH_BLOGS_REQUEST = 'blogs/FETCH_BLOGS_REQUEST';
export const FETCH_BLOGS_SUCCESS = 'blogs/FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILURE = 'blogs/FETCH_BLOGS_FAILURE';

export const FETCH_SINGLE_BLOG_REQUEST = 'blogs/FETCH_SINGLE_BLOG_REQUEST';
export const FETCH_SINGLE_BLOG_SUCCESS = 'blogs/FETCH_SINGLE_BLOG_SUCCESS';
export const FETCH_SINGLE_BLOG_FAILURE = 'blogs/FETCH_SINGLE_BLOG_FAILURE';
