export const FETCH_INSTALLMENT_GATEWAYS_REQUEST =
  "general/FETCH_INSTALLMENT_GATEWAYS_REQUEST";
export const FETCH_INSTALLMENT_GATEWAYS_SUCCESS =
  "general/FETCH_INSTALLMENT_GATEWAYS_SUCCESS";
export const FETCH_INSTALLMENT_GATEWAYS_FAILURE =
  "general/FETCH_INSTALLMENT_GATEWAYS_FAILURE";
