export const FETCH_INSTALLMENT_GATEWAYS_REQUEST =
  "general/FETCH_INSTALLMENT_GATEWAYS_REQUEST";
export const FETCH_INSTALLMENT_GATEWAYS_SUCCESS =
  "general/FETCH_INSTALLMENT_GATEWAYS_SUCCESS";
export const FETCH_INSTALLMENT_GATEWAYS_FAILURE =
  "general/FETCH_INSTALLMENT_GATEWAYS_FAILURE";

export const FETCH_HEADER_MENUS_REQUEST = "general/FETCH_HEADER_MENUS_REQUEST";
export const FETCH_HEADER_MENUS_SUCCESS = "general/FETCH_HEADER_MENUS_SUCCESS";
export const FETCH_HEADER_MENUS_FAILURE = "general/FETCH_HEADER_MENUS_FAILURE";

export const FETCH_COUNTRIES_REQUEST = "general/FETCH_COUNTRIES_REQUEST";
export const FETCH_COUNTRIES_SUCCESS = "general/FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "general/FETCH_COUNTRIES_FAILURE";

export const FETCH_SEARCH_REQUEST = "general/FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "general/FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "general/FETCH_SEARCH_FAILURE";
