export const FETCH_INSTALLMENT_CART_REQUEST =
  "installmentCart/FETCH_INSTALLMENT_CART_REQUEST";
export const FETCH_INSTALLMENT_CART_SUCCESS =
  "installmentCart/FETCH_INSTALLMENT_CART_SUCCESS";
export const FETCH_INSTALLMENT_CART_FAILURE =
  "installmentCart/FETCH_INSTALLMENT_CART_FAILURE";

export const ADD_TO_INSTALLMENT_CART_REQUEST =
  "installmentCart/ADD_TO_INSTALLMENT_CART_REQUEST";
export const ADD_TO_INSTALLMENT_CART_SUCCESS =
  "installmentCart/ADD_TO_INSTALLMENT_CART_SUCCESS";
export const ADD_TO_INSTALLMENT_CART_FAILURE =
  "installmentCart/ADD_TO_INSTALLMENT_CART_FAILURE";

export const REMOVE_FROM_INSTALLMENT_CART_REQUEST =
  "installmentCart/REMOVE_FROM_INSTALLMENT_CART_REQUEST";
export const REMOVE_FROM_INSTALLMENT_CART_SUCCESS =
  "installmentCart/REMOVE_FROM_INSTALLMENT_CART_SUCCESS";
export const REMOVE_FROM_INSTALLMENT_CART_FAILURE =
  "installmentCart/REMOVE_FROM_INSTALLMENT_CART_FAILURE";

export const UPDATE_INSTALLMENT_CART_ITEM_REQUEST =
  "installmentCart/UPDATE_INSTALLMENT_CART_ITEM_REQUEST";
export const UPDATE_INSTALLMENT_CART_ITEM_SUCCESS =
  "installmentCart/UPDATE_INSTALLMENT_CART_ITEM_SUCCESS";
export const UPDATE_INSTALLMENT_CART_ITEM_FAILURE =
  "installmentCart/UPDATE_INSTALLMENT_CART_ITEM_FAILURE";

export const CLEAR_INSTALLMENT_CART = "installmentCart/CLEAR_INSTALLMENT_CART";
