export const FETCH_FAVORITES_REQUEST = 'favorites/FETCH_FAVORITES_REQUEST';
export const FETCH_FAVORITES_SUCCESS = 'favorites/FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAILURE = 'favorites/FETCH_FAVORITES_FAILURE';

export const ADD_TO_FAVORITES_REQUEST = 'favorites/ADD_TO_FAVORITES_REQUEST';
export const ADD_TO_FAVORITES_SUCCESS = 'favorites/ADD_TO_FAVORITES_SUCCESS';
export const ADD_TO_FAVORITES_FAILURE = 'favorites/ADD_TO_FAVORITES_FAILURE';

export const REMOVE_FROM_FAVORITES_REQUEST =
 'favorites/REMOVE_FROM_FAVORITES_REQUEST';
export const REMOVE_FROM_FAVORITES_SUCCESS =
 'favorites/REMOVE_FROM_FAVORITES_SUCCESS';
export const REMOVE_FROM_FAVORITES_FAILURE =
 'favorites/REMOVE_FROM_FAVORITES_FAILURE';
