export const FETCH_PRODUCTS_REQUEST = 'products/FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'products/FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'products/FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_DETAILS_REQUEST =
 'products/FETCH_PRODUCT_DETAILS_REQUEST';
export const FETCH_PRODUCT_DETAILS_SUCCESS =
 'products/FETCH_PRODUCT_DETAILS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_FAILURE =
 'products/FETCH_PRODUCT_DETAILS_FAILURE';
