export const FETCH_USER_PROFILE_REQUEST = "user/FETCH_USER_PROFILE_REQUEST";
export const FETCH_USER_PROFILE_SUCCESS = "user/FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILURE = "user/FETCH_USER_PROFILE_FAILURE";

export const UPDATE_USER_PROFILE_REQUEST = "user/UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "user/UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "user/UPDATE_USER_PROFILE_FAILURE";

// Addresses
export const FETCH_ADDRESSES_REQUEST = "user/FETCH_ADDRESSES_REQUEST";
export const FETCH_ADDRESSES_SUCCESS = "user/FETCH_ADDRESSES_SUCCESS";
export const FETCH_ADDRESSES_FAILURE = "user/FETCH_ADDRESSES_FAILURE";

export const ADD_ADDRESS_REQUEST = "user/ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "user/ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILURE = "user/ADD_ADDRESS_FAILURE";

export const UPDATE_ADDRESS_REQUEST = "user/UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "user/UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE = "user/UPDATE_ADDRESS_FAILURE";

export const DELETE_ADDRESS_REQUEST = "user/DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "user/DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "user/DELETE_ADDRESS_FAILURE";

// Orders
export const FETCH_ORDERS_REQUEST = "user/FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "user/FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "user/FETCH_ORDERS_FAILURE";

// Favorites
export const FETCH_FAVORITES_REQUEST = "user/FETCH_FAVORITES_REQUEST";
export const FETCH_FAVORITES_SUCCESS = "user/FETCH_FAVORITES_SUCCESS";
export const FETCH_FAVORITES_FAILURE = "user/FETCH_FAVORITES_FAILURE";
export const ADD_FAVORITE_REQUEST = "user/ADD_FAVORITE_REQUEST";
export const ADD_FAVORITE_SUCCESS = "user/ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAILURE = "user/ADD_FAVORITE_FAILURE";
export const REMOVE_FAVORITE_REQUEST = "user/REMOVE_FAVORITE_REQUEST";
export const REMOVE_FAVORITE_SUCCESS = "user/REMOVE_FAVORITE_SUCCESS";
export const REMOVE_FAVORITE_FAILURE = "user/REMOVE_FAVORITE_FAILURE";

// Tickets
export const FETCH_TICKETS_REQUEST = "user/FETCH_TICKETS_REQUEST";
export const FETCH_TICKETS_SUCCESS = "user/FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAILURE = "user/FETCH_TICKETS_FAILURE";
export const CREATE_TICKET_REQUEST = "user/CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "user/CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAILURE = "user/CREATE_TICKET_FAILURE";
export const REPLY_TICKET_REQUEST = "user/REPLY_TICKET_REQUEST";
export const REPLY_TICKET_SUCCESS = "user/REPLY_TICKET_SUCCESS";
export const REPLY_TICKET_FAILURE = "user/REPLY_TICKET_FAILURE";

// Wallet & Transactions
export const FETCH_WALLET_REQUEST = "user/FETCH_WALLET_REQUEST";
export const FETCH_WALLET_SUCCESS = "user/FETCH_WALLET_SUCCESS";
export const FETCH_WALLET_FAILURE = "user/FETCH_WALLET_FAILURE";
export const FETCH_TRANSACTIONS_REQUEST = "user/FETCH_TRANSACTIONS_REQUEST";
export const FETCH_TRANSACTIONS_SUCCESS = "user/FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAILURE = "user/FETCH_TRANSACTIONS_FAILURE";
