export const ADD_TO_COMPARE_SUCCESS = "compare/ADD_TO_COMPARE_SUCCESS";
export const REMOVE_FROM_COMPARE_REQUEST =
  "compare/REMOVE_FROM_COMPARE_REQUEST";
export const REMOVE_FROM_COMPARE_SUCCESS =
  "compare/REMOVE_FROM_COMPARE_SUCCESS";
export const CLEAR_COMPARE_REQUEST = "compare/CLEAR_COMPARE_REQUEST";
export const CLEAR_COMPARE_SUCCESS = "compare/CLEAR_COMPARE_SUCCESS";
export const TOGGLE_COMPARE_REQUEST = "compare/TOGGLE_COMPARE_REQUEST";
