export const CREATE_ORDER_REQUEST = 'orders/CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'orders/CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'orders/CREATE_ORDER_FAILURE';

export const FETCH_ORDERS_REQUEST = 'orders/FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'orders/FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'orders/FETCH_ORDERS_FAILURE';

export const CANCEL_ORDER_REQUEST = 'orders/CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'orders/CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'orders/CANCEL_ORDER_FAILURE';
