export const FETCH_INITIAL_STATE_REQUEST =
  "initialState/FETCH_INITIAL_STATE_REQUEST";
export const FETCH_INITIAL_STATE_SUCCESS =
  "initialState/FETCH_INITIAL_STATE_SUCCESS";
export const FETCH_INITIAL_STATE_FAILURE =
  "initialState/FETCH_INITIAL_STATE_FAILURE";